=== Oufti2015/workflow/src/main/xsd/SSTWorkflow.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2014 rel. 2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="job">
		<xs:complexType>
			<xs:attribute name="class" use="required" type="xs:string"/>
			<xs:attribute name="sequence" use="required" type="xs:long"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="jobs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="job" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="task">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dependencies" minOccurs="0"/>
				<xs:element ref="jobs"/>
			</xs:sequence>
			<xs:attribute name="id" use="required" type="xs:string"/>
			<xs:attribute name="exit" type="xs:boolean" default="false"/>
			<xs:attribute name="entry" type="xs:boolean" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="workflow">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="task" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dependency">
		<xs:complexType>
			<xs:attribute name="dependsOn" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dependencies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dependency" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Oufti2015/workflow/wf-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<workflow xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/zt974/git/repo_perso/SSTWorkflow/SSTWorkflow.xsd">
	<task id="A" entry="true">
		<jobs>
			<job sequence="1" class="sst.workflow.jobs.jobA1"/>
			<job sequence="2" class="sst.workflow.jobs.jobA2"/>
			<job sequence="3" class="sst.workflow.jobs.jobA3"/>
		</jobs>
	</task>
	<task id="B">
		<dependencies>
			<dependency dependsOn="A"/>
		</dependencies>
		<jobs>
			<job sequence="1" class="sst.workflow.jobs.jobB1"/>
			<job sequence="2" class="sst.workflow.jobs.jobB2"/>
		</jobs>
	</task>
	<task id="C">
		<dependencies>
			<dependency dependsOn="B"/>
		</dependencies>
		<jobs>
			<job sequence="1" class="sst.workflow.jobs.jobC1"/>
		</jobs>
	</task>
	<task id="D">
		<dependencies>
			<dependency dependsOn="B"/>
		</dependencies>
		<jobs>
			<job sequence="1" class="sst.workflow.jobs.jobD1"/>
		</jobs>
	</task>
	<task id="E">
		<dependencies>
			<dependency dependsOn="B"/>
		</dependencies>
		<jobs>
			<job sequence="1" class="sst.workflow.jobs.jobE1"/>
		</jobs>
	</task>
	<task id="F">
		<dependencies>
			<dependency dependsOn="D"/>
			<dependency dependsOn="E"/>
		</dependencies>
		<jobs>
			<job sequence="1" class="sst.workflow.jobs.jobF1"/>
		</jobs>
	</task>
	<task id="G">
		<dependencies>
			<dependency dependsOn="C"/>
		</dependencies>
		<jobs>
			<job sequence="1" class="sst.workflow.jobs.jobG1"/>
			<job sequence="1" class="sst.workflow.jobs.jobG2"/>
		</jobs>
	</task>
	<task id="H" exit="true">
		<dependencies>
			<dependency dependsOn="F"/>
			<dependency dependsOn="G"/>
		</dependencies>
		<jobs>
			<job sequence="1" class="sst.workflow.jobs.jobH1"/>
		</jobs>
	</task>
</workflow>
